<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(TargetFrameworks)</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cike.EventBus.Local\Cike.EventBus.Local.csproj" />
		<ProjectReference Include="..\Cike.EventBus\Cike.EventBus.csproj" />
	</ItemGroup>

</Project>
